TodoApp/Pages/EditTodo.cshtml.cs
using AutoMapper;
using Data.Repositories.Abstractions;
using Data.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TodoApp.Pages
{
    [BindProperties]
    public class EditTodoModel : PageModel
    {
        private readonly ITaskRepository _repo;

        private readonly IMapper _mapper;
        public TaskViewModel Task { get; set; }
        public EditTodoModel(ITaskRepository repo, IMapper mapper)
        {
            _repo = repo;
            _mapper = mapper;
        }

        public async Task<IActionResult> OnGet(int id)
        {
            var task = await _repo.GetTaskById(id);
            Task = _mapper.Map<TaskViewModel>(task);
            return Page();

        }

        public async Task<IActionResult> OnPost()
        {
            var task = _mapper.Map<Data.Models.Task>(Task);   
            await _repo.EditTask(task);
            return RedirectToPage("Index");
        }
    }
}

TodoApp/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace TodoApp.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

TodoApp/Pages/Index.cshtml.cs
using AutoMapper;
using Data.Repositories.Abstractions;
using Data.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TodoApp.Services;

namespace TodoApp.Pages
{
    [BindProperties(SupportsGet = true)]
    public class IndexModel : PageModel
    {
       
        private readonly ITaskService _service;
        public TaskViewModel Task { get; set; }
        public string SearchQuery { get; set; }
        public DateTime Date { get; set; } = DateTime.Now.Date;

        public IndexModel(ITaskService service)
        {
            _service = service;
        }
        
        public IList<TaskViewModel> Tasks { get; set; }

        public async Task<IActionResult> OnGet()
        {
            if(string.IsNullOrEmpty(SearchQuery))
            {
                Tasks = await _service.GetAllTasks();
            }
            else
            {
                Tasks = await _service.FindTasks(SearchQuery);
            }
            
           
            return Page();
        }

        public async Task<IActionResult> OnPostSearchByDate()
        {
            Tasks = await _service.FindByDate(Date);
            return Page();
        }

        public async Task<IActionResult> OnPostAdd()
        {
            if(!string.IsNullOrEmpty(Task.TodoTask))
            {
                await _service.CreateTask(Task);
            }
            
            Task = new TaskViewModel();

            return RedirectToPage("Index");
        }

        public async Task<IActionResult> OnPostDelete(int id)
        {
            await _service.DeleteTaskById(id);

            return RedirectToPage("Index");
        }

        public async Task<IActionResult> OnPostDeleteSelected()
        {
            var ids = new List<int>();
            foreach(var task in Tasks)
            {
                if(task.Check)
                    ids.Add(task.Id);
            }
            await _service.DeleteMultpleTasks(ids);
            return RedirectToPage("Index");
        }

    }
}

TodoApp/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TodoApp.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

TodoApp/Pages/EditTodo.cshtml
@page
@model TodoApp.Pages.EditTodoModel
@{
    ViewData["Title"] = "Edit Todo";
}
<section class="vh-100">
  <div class="container  h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col">
        <div class="card" id="list1" style="border-radius: .75rem; background-color: #eff1f2;">
          <div class="card-body py-4 px-4 px-md-5">

            <p class="h1 text-center mt-3 mb-4 pb-3 text-primary">
              <i class="fas fa-check-square me-1"></i>
              <u>My Todo-s</u>
            </p>

            <div class="pb-2">
              <div class="card">
                <div class="card-body">
                 
                    <form method="post" class="d-flex flex-row align-items-center">
                        <input type="text" class="form-control form-control-lg" asp-for="Task.TodoTask"
                      placeholder="Add new...">
                      <input type="text" asp-for="Task.Id" hidden/>
                      <input type="text" asp-for="Task.Date" hidden>

                   <!-- <a href="#!" data-mdb-toggle="tooltip" title="Set due date"><i
                        class="fas fa-calendar-alt fa-lg me-3"></i></a>-->
                    <div>
                      <button type="submit" class="btn btn-primary" asp-page-handler="Edit">Edit</button>
                    </div>
                    </form>
       
                 
                </div>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
</section>

TodoApp/Pages/Index.cshtml
@page 
@model IndexModel
@{
    ViewData["Title"] = "Todo page";
}

<section class="vh-100">
  <div class="container  h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col">
        <div class="card" id="list1" style="border-radius: .75rem; background-color: #eff1f2;">
          <div class="card-body py-4 px-4 px-md-5">

            <p class="h1 text-center mt-3 mb-4 pb-3 text-primary">
              <i class="fas fa-check-square me-1"></i>
              <u>My Todo-s</u>
            </p>

            <div class="pb-2">
             
                 <div class="d-flex justify-content-center align-items-center">
                     <form method="post" class="d-flex flex-row align-items-center me-5">
                        <input type="text" class="form-control form-control-lg" asp-for="Task.TodoTask"
                      placeholder="Add new...">
                   <!-- <a href="#!" data-mdb-toggle="tooltip" title="Set due date"><i
                        class="fas fa-calendar-alt fa-lg me-3"></i></a>-->
                    <div>
                      <button type="submit" class="btn btn-primary ms-2" asp-page-handler="Add"><i class="fa fa-plus" aria-hidden="true"></i></button>
                    </div>
                    </form>

                   <form class="d-flex flex-row align-items-center ms-5">
                        <input type="text" class="form-control form-control-lg" asp-for="SearchQuery"
                      placeholder="Search...">
                   <!-- <a href="#!" data-mdb-toggle="tooltip" title="Set due date"><i
                        class="fas fa-calendar-alt fa-lg me-3"></i></a>-->
                    <div>
                   
                      <button type="submit"  class="btn btn-primary ms-2" ><i class="fas fa-search"></i></button>
                    </div>
                    </form>

                    <form method="post" class="d-flex flex-row align-items-center ms-5">
                         <input type="date" asp-for="Date" class="form-control form-control-lg">
                     
                     <div>
                      <button asp-page-handler="SearchByDate" type="submit" class="btn btn-primary ms-2" ><i class="fas fa-search"></i></button>
                    </div>
                     </form>

                 </div>
                    
                 
              
            </div>

            <hr class="my-4">

           
            
 
     <form method="post">
        
             @for(int i = 0; i < Model.Tasks.Count(); i++)
             {
                                  <ul class="list-group list-group-horizontal rounded-0 bg-transparent">
              <li
                class="list-group-item d-flex align-items-center ps-0 pe-3 py-1 rounded-0 border-0 bg-transparent">
                <div class="form-check">
                  <input class="form-check-input me-0" asp-for="@Model.Tasks[i].Check" />
                   <input class="form-check-input me-0" asp-for="@Model.Tasks[i].Id" hidden />

                </div>
              </li>
              <li
                class="list-group-item px-3 py-1 d-flex align-items-center flex-grow-1 border-0 bg-transparent">
                <p class="lead fw-normal mb-0">@Model.Tasks[i].TodoTask</p>
              </li>
              <li class="list-group-item ps-3 pe-0 py-1 rounded-0 border-0 bg-transparent">
                <div class="d-flex flex-row justify-content-end mb-1">
                  <a asp-page="EditTodo" asp-route-id="@Model.Tasks[i].Id" class="text-info" data-mdb-toggle="tooltip" title="Edit todo"><i
                      class="fas fa-pencil-alt me-3"></i></a>
                
                 <button type="submit" asp-page-handler="Delete" asp-route-id="@Model.Tasks[i].Id" class="text-danger fas fa-trash-alt no-border" data-mdb-toggle="tooltip"></button>
               
                 
                </div>
                <div class="text-end text-muted">
                  <a href="#!" class="text-muted" data-mdb-toggle="tooltip" title="Created date">
                    <p class="small mb-0"><i class="fas fa-info-circle me-2"></i>@Model.Tasks[i].Date</p>
                  </a>
                </div>
              </li>
            </ul>
            }
              <div class="d-flex justify-content-end align-items-center mb-4 pt-2 pb-3">
              
                 <button type="submit" asp-page-handler="DeleteSelected" class="btn btn-outline-danger" data-mdb-toggle="tooltip">Delete Selected</button>
                
            </div>
             </form>
 

          </div>
        </div>
      </div>
    </div>
  </div>
</section>

TodoApp/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TodoApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <script src="https://kit.fontawesome.com/f52ddf1039.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TodoApp.styles.css" asp-append-version="true" />
</head>
<body>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>